# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.sistema import Sistema  # noqa: F401,E501
from swagger_server.models.tipo_historico import TipoHistorico  # noqa: F401,E501
from swagger_server import util


class Historico(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, data: datetime=None, tipo: TipoHistorico=None, sistema: Sistema=None, descricao: str=None):  # noqa: E501
        """Historico - a model defined in Swagger

        :param id: The id of this Historico.  # noqa: E501
        :type id: int
        :param data: The data of this Historico.  # noqa: E501
        :type data: datetime
        :param tipo: The tipo of this Historico.  # noqa: E501
        :type tipo: TipoHistorico
        :param sistema: The sistema of this Historico.  # noqa: E501
        :type sistema: Sistema
        :param descricao: The descricao of this Historico.  # noqa: E501
        :type descricao: str
        """
        self.swagger_types = {
            'id': int,
            'data': datetime,
            'tipo': TipoHistorico,
            'sistema': Sistema,
            'descricao': str
        }

        self.attribute_map = {
            'id': 'id',
            'data': 'data',
            'tipo': 'tipo',
            'sistema': 'sistema',
            'descricao': 'descricao'
        }
        self._id = id
        self._data = data
        self._tipo = tipo
        self._sistema = sistema
        self._descricao = descricao

    @classmethod
    def from_dict(cls, dikt) -> 'Historico':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Historico of this Historico.  # noqa: E501
        :rtype: Historico
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Historico.


        :return: The id of this Historico.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Historico.


        :param id: The id of this Historico.
        :type id: int
        """

        self._id = id

    @property
    def data(self) -> datetime:
        """Gets the data of this Historico.


        :return: The data of this Historico.
        :rtype: datetime
        """
        return self._data

    @data.setter
    def data(self, data: datetime):
        """Sets the data of this Historico.


        :param data: The data of this Historico.
        :type data: datetime
        """

        self._data = data

    @property
    def tipo(self) -> TipoHistorico:
        """Gets the tipo of this Historico.


        :return: The tipo of this Historico.
        :rtype: TipoHistorico
        """
        return self._tipo

    @tipo.setter
    def tipo(self, tipo: TipoHistorico):
        """Sets the tipo of this Historico.


        :param tipo: The tipo of this Historico.
        :type tipo: TipoHistorico
        """

        self._tipo = tipo

    @property
    def sistema(self) -> Sistema:
        """Gets the sistema of this Historico.


        :return: The sistema of this Historico.
        :rtype: Sistema
        """
        return self._sistema

    @sistema.setter
    def sistema(self, sistema: Sistema):
        """Sets the sistema of this Historico.


        :param sistema: The sistema of this Historico.
        :type sistema: Sistema
        """

        self._sistema = sistema

    @property
    def descricao(self) -> str:
        """Gets the descricao of this Historico.


        :return: The descricao of this Historico.
        :rtype: str
        """
        return self._descricao

    @descricao.setter
    def descricao(self, descricao: str):
        """Sets the descricao of this Historico.


        :param descricao: The descricao of this Historico.
        :type descricao: str
        """

        self._descricao = descricao
