# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.historico import Historico  # noqa: F401,E501
from swagger_server.models.retorno import Retorno  # noqa: F401,E501
from swagger_server import util


class RetornoHistorico(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, codigo: int=None, descricao: str=None, registros: int=None, pagina: int=None, qtde_pagina: int=None, lista_historicos: List[Historico]=None):  # noqa: E501
        """RetornoHistorico - a model defined in Swagger

        :param codigo: The codigo of this RetornoHistorico.  # noqa: E501
        :type codigo: int
        :param descricao: The descricao of this RetornoHistorico.  # noqa: E501
        :type descricao: str
        :param registros: The registros of this RetornoHistorico.  # noqa: E501
        :type registros: int
        :param pagina: The pagina of this RetornoHistorico.  # noqa: E501
        :type pagina: int
        :param qtde_pagina: The qtde_pagina of this RetornoHistorico.  # noqa: E501
        :type qtde_pagina: int
        :param lista_historicos: The lista_historicos of this RetornoHistorico.  # noqa: E501
        :type lista_historicos: List[Historico]
        """
        self.swagger_types = {
            'codigo': int,
            'descricao': str,
            'registros': int,
            'pagina': int,
            'qtde_pagina': int,
            'lista_historicos': List[Historico]
        }

        self.attribute_map = {
            'codigo': 'codigo',
            'descricao': 'descricao',
            'registros': 'registros',
            'pagina': 'pagina',
            'qtde_pagina': 'qtdePagina',
            'lista_historicos': 'listaHistoricos'
        }
        self._codigo = codigo
        self._descricao = descricao
        self._registros = registros
        self._pagina = pagina
        self._qtde_pagina = qtde_pagina
        self._lista_historicos = lista_historicos

    @classmethod
    def from_dict(cls, dikt) -> 'RetornoHistorico':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RetornoHistorico of this RetornoHistorico.  # noqa: E501
        :rtype: RetornoHistorico
        """
        return util.deserialize_model(dikt, cls)

    @property
    def codigo(self) -> int:
        """Gets the codigo of this RetornoHistorico.


        :return: The codigo of this RetornoHistorico.
        :rtype: int
        """
        return self._codigo

    @codigo.setter
    def codigo(self, codigo: int):
        """Sets the codigo of this RetornoHistorico.


        :param codigo: The codigo of this RetornoHistorico.
        :type codigo: int
        """

        self._codigo = codigo

    @property
    def descricao(self) -> str:
        """Gets the descricao of this RetornoHistorico.


        :return: The descricao of this RetornoHistorico.
        :rtype: str
        """
        return self._descricao

    @descricao.setter
    def descricao(self, descricao: str):
        """Sets the descricao of this RetornoHistorico.


        :param descricao: The descricao of this RetornoHistorico.
        :type descricao: str
        """

        self._descricao = descricao

    @property
    def registros(self) -> int:
        """Gets the registros of this RetornoHistorico.


        :return: The registros of this RetornoHistorico.
        :rtype: int
        """
        return self._registros

    @registros.setter
    def registros(self, registros: int):
        """Sets the registros of this RetornoHistorico.


        :param registros: The registros of this RetornoHistorico.
        :type registros: int
        """

        self._registros = registros

    @property
    def pagina(self) -> int:
        """Gets the pagina of this RetornoHistorico.


        :return: The pagina of this RetornoHistorico.
        :rtype: int
        """
        return self._pagina

    @pagina.setter
    def pagina(self, pagina: int):
        """Sets the pagina of this RetornoHistorico.


        :param pagina: The pagina of this RetornoHistorico.
        :type pagina: int
        """

        self._pagina = pagina

    @property
    def qtde_pagina(self) -> int:
        """Gets the qtde_pagina of this RetornoHistorico.


        :return: The qtde_pagina of this RetornoHistorico.
        :rtype: int
        """
        return self._qtde_pagina

    @qtde_pagina.setter
    def qtde_pagina(self, qtde_pagina: int):
        """Sets the qtde_pagina of this RetornoHistorico.


        :param qtde_pagina: The qtde_pagina of this RetornoHistorico.
        :type qtde_pagina: int
        """

        self._qtde_pagina = qtde_pagina

    @property
    def lista_historicos(self) -> List[Historico]:
        """Gets the lista_historicos of this RetornoHistorico.


        :return: The lista_historicos of this RetornoHistorico.
        :rtype: List[Historico]
        """
        return self._lista_historicos

    @lista_historicos.setter
    def lista_historicos(self, lista_historicos: List[Historico]):
        """Sets the lista_historicos of this RetornoHistorico.


        :param lista_historicos: The lista_historicos of this RetornoHistorico.
        :type lista_historicos: List[Historico]
        """

        self._lista_historicos = lista_historicos
